import React, { useEffect } from "react";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { motion } from "framer-motion";
import { Printer, BookOpen, FileText, HelpCircle, CreditCard, Truck, RefreshCw, Search, Shield } from "lucide-react";

// FAQ data with categorization (categories kept for icons only)

const faqs = [
  {
    question: "What types of printing services do you offer?",
    answer: "We offer black & white and color printing on various paper types including normal paper, bond paper (80 GSM, 90 GSM, 100 GSM). We specialize in academic document printing with high-quality outputs suitable for thesis, research papers, and projects.",
    category: "printing",
    icon: <Printer className="h-5 w-5" />
  },
  {
    question: "How long does it take to bind a thesis or dissertation?",
    answer: "Binding time depends on the type of binding and our current queue. Hard binding typically takes 24-48 hours, while soft and spiral binding can usually be completed within a few hours. For urgent requests, we offer express services at an additional charge.",
    category: "binding",
    icon: <BookOpen className="h-5 w-5" />
  },
  {
    question: "What is the difference between the types of hard binding?",
    answer: "Normal hard binding uses standard materials suitable for regular use. High-quality binding uses premium materials with better durability. Gloss quality adds a glossy finish to the cover, while emboss quality includes raised text/design on the cover (minimum 4 copies required for emboss binding).",
    category: "binding",
    icon: <BookOpen className="h-5 w-5" />
  },
  {
    question: "How does your plagiarism checking service work?",
    answer: "We use industry-standard tools like Turnitin to check your document against billions of web pages, publications, and student papers. You'll receive a detailed report showing overall similarity percentage and specific matches, allowing you to make necessary changes.",
    category: "plagiarism",
    icon: <Search className="h-5 w-5" />
  },
  {
    question: "What is AI plagiarism checking and how is it different?",
    answer: "AI plagiarism checking detects content that may have been generated by AI tools like ChatGPT, which traditional plagiarism checkers might miss. This is increasingly important as many academic institutions are implementing policies against AI-generated content.",
    category: "plagiarism",
    icon: <Shield className="h-5 w-5" />
  },
  {
    question: "Do you provide academic writing assistance for all subjects?",
    answer: "Yes, we provide academic writing assistance across various disciplines including business, engineering, medicine, humanities, and social sciences. Our team includes subject-matter experts with advanced degrees who can help with thesis writing, research papers, and other academic documents.",
    category: "academic",
    icon: <FileText className="h-5 w-5" />
  },
  {
    question: "What payment methods do you accept?",
    answer: "We accept cash, UPI payments, bank transfers, and major credit/debit cards. For large orders, we may request a partial advance payment.",
    category: "general",
    icon: <CreditCard className="h-5 w-5" />
  },
  {
    question: "Do you offer bulk discounts for printing and binding?",
    answer: "Yes, we offer bulk discounts for orders exceeding specific thresholds. The discount percentage depends on the volume and type of services requested. Please contact us directly for a custom quote for your bulk order.",
    category: "general",
    icon: <HelpCircle className="h-5 w-5" />
  },
  {
    question: "Can you deliver printed and bound documents?",
    answer: "For orders above a certain value, we offer delivery services within select areas. Additional delivery charges may apply based on the location. Please inquire about delivery options when placing your order.",
    category: "general",
    icon: <Truck className="h-5 w-5" />
  },
  {
    question: "What is your revision policy for plagiarism removal services?",
    answer: "We offer up to two rounds of revisions for our plagiarism removal services at no extra cost if the similarity score remains above the acceptable threshold. Additional revisions may incur extra charges depending on the extent of changes required.",
    category: "plagiarism",
    icon: <RefreshCw className="h-5 w-5" />
  }
];

const Faq = () => {
  // Animation variants
  const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: {
        staggerChildren: 0.05,
        delayChildren: 0.1
      }
    }
  };

  const itemVariants = {
    hidden: { opacity: 0, y: 20 },
    visible: {
      opacity: 1,
      y: 0,
      transition: {
        type: "spring",
        stiffness: 300,
        damping: 24
      }
    }
  };
  
  // Add keyframe animations through JavaScript
  useEffect(() => {
    const styleEl = document.createElement('style');
    styleEl.textContent = `
      @keyframes shimmer {
        0% {
          background-position: -200px 0;
        }
        100% {
          background-position: calc(200px + 100%) 0;
        }
      }
      
      .faq-shimmer {
        position: relative;
        overflow: hidden;
      }
      
      .faq-shimmer::after {
        content: '';
        position: absolute;
        top: -50%;
        left: -50%;
        right: -50%;
        bottom: -50%;
        background: linear-gradient(
          to right,
          rgba(255, 255, 255, 0) 0%,
          rgba(255, 255, 255, 0.1) 50%,
          rgba(255, 255, 255, 0) 100%
        );
        transform: rotate(30deg);
        animation: shimmer 4s infinite;
        pointer-events: none;
      }

      .faq-card {
        position: relative;
        z-index: 1;
      }
      
      .faq-card::before {
        content: '';
        position: absolute;
        z-index: -1;
        top: 0;
        right: 0;
        bottom: 0;
        left: 0;
        background: linear-gradient(to bottom right, rgba(212, 175, 55, 0.05), rgba(184, 134, 11, 0.1));
        transform: scale(0.95);
        filter: blur(20px);
        opacity: 0;
        transition: opacity 0.3s;
        border-radius: inherit;
      }
      
      .faq-card:hover::before {
        opacity: 1;
      }
    `;
    
    // Append the style element to the head
    document.head.appendChild(styleEl);
    
    // Clean up on component unmount
    return () => {
      document.head.removeChild(styleEl);
    };
  }, []);

  return (
    <section id="faq" className="py-16 md:py-24 bg-gradient-to-b from-white to-[#f9f7ed] relative overflow-hidden">
      {/* Decorative elements */}
      <div className="absolute top-10 left-10 w-40 h-40 bg-[#D4AF37]/5 rounded-full blur-3xl"></div>
      <div className="absolute bottom-10 right-10 w-60 h-60 bg-[#B8860B]/5 rounded-full blur-3xl"></div>
      <div className="absolute top-1/2 left-1/3 w-20 h-20 bg-[#D4AF37]/10 rounded-full blur-2xl"></div>

      <div className="container px-4 sm:px-6 lg:px-8 relative">
        <motion.div 
          className="text-center max-w-4xl mx-auto mb-12"
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
        >
          <div className="inline-block mb-3 px-4 py-1 bg-[#D4AF37]/10 rounded-full">
            <span className="text-sm font-medium text-[#B8860B]">Got Questions?</span>
          </div>

          <h2 className="font-serif text-3xl md:text-5xl font-bold mb-6 relative inline-block">
            <span className="bg-gradient-to-r from-[#D4AF37] to-[#B8860B] bg-clip-text text-transparent">Frequently Asked</span> <span className="text-gray-900">Questions</span>
          </h2>
          <p className="text-gray-600 text-lg max-w-2xl mx-auto">
            Find answers to common questions about our services. Can't find what you're looking for? Contact us directly.
          </p>
        </motion.div>
        
        {/* Spacing element - removed category filter tabs */}
        <div className="h-4"></div>
        
        <motion.div 
          className="max-w-4xl mx-auto grid grid-cols-1 lg:grid-cols-12 gap-8"
          variants={containerVariants}
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, amount: 0.2 }}
        >
          {/* Main FAQ Content */}
          <div className="lg:col-span-12">
            <motion.div 
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5 }}
              className="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden faq-card"
            >
              <Accordion type="single" collapsible className="w-full">
                {faqs.map((faq, index) => (
                    <motion.div key={index} variants={itemVariants}>
                      <AccordionItem value={`item-${index}`} className="border-b border-gray-100 last:border-b-0">
                        <AccordionTrigger className="px-6 py-4 hover:no-underline group data-[state=open]:text-[#B8860B]">
                          <div className="flex items-center text-left">
                            <span className="flex-shrink-0 h-8 w-8 rounded-full bg-[#D4AF37]/10 flex items-center justify-center mr-3 group-hover:bg-[#D4AF37]/20 transition-colors duration-300">
                              {faq.icon}
                            </span>
                            <span className="font-medium text-gray-900 group-hover:text-[#B8860B] transition-colors duration-300">
                              {faq.question}
                            </span>
                          </div>
                        </AccordionTrigger>
                        <AccordionContent className="px-6 pb-4 pt-0 text-gray-600">
                          <motion.div 
                            initial={{ opacity: 0 }}
                            animate={{ opacity: 1 }}
                            transition={{ duration: 0.3 }}
                            className="pl-11 text-base"
                          >
                            {faq.answer}
                          </motion.div>
                        </AccordionContent>
                      </AccordionItem>
                    </motion.div>
                  ))}
                </Accordion>
              </motion.div>
          </div>
        </motion.div>
        
        {/* Still have questions? */}
        <motion.div 
          className="mt-16 max-w-3xl mx-auto"
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
        >
          <motion.div 
            className="bg-white rounded-xl border border-gray-200 p-8 relative overflow-hidden shadow-lg faq-shimmer"
            whileHover={{ y: -5 }}
            transition={{ type: "spring", stiffness: 400, damping: 17 }}
          >
            <div className="relative z-10 pointer-events-auto">
              <div className="h-16 w-16 mx-auto bg-gradient-to-r from-[#D4AF37] to-[#B8860B] rounded-full flex items-center justify-center mb-4 shadow-lg">
                <HelpCircle className="h-8 w-8 text-white" />
              </div>
              
              <h3 className="font-serif text-2xl font-bold text-center text-gray-900 mb-4">Still have questions?</h3>
              <p className="text-center text-gray-600 mb-8 max-w-lg mx-auto">
                Can't find the answer you're looking for? Feel free to reach out to our customer support team.
              </p>
              
              <div className="flex flex-col sm:flex-row justify-center gap-4 flex-wrap">
                <motion.a 
                  href="https://wa.me/919311244099"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-center justify-center px-6 py-3 rounded-lg bg-green-500 text-white font-medium transition-all duration-300 hover:bg-green-600 hover:shadow-lg"
                  whileHover={{ scale: 1.05 }}
                  whileTap={{ scale: 0.95 }}
                >
                  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" className="h-5 w-5 mr-2">
                    <path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 00-3.48-8.413z"/>
                  </svg>
                  WhatsApp Us
                </motion.a>
                
                <motion.a 
                  href="#contact"
                  className="inline-flex items-center justify-center px-6 py-3 rounded-lg bg-gradient-to-r from-[#D4AF37] to-[#B8860B] text-white font-medium transition-all duration-300 hover:shadow-lg"
                  whileHover={{ scale: 1.05 }}
                  whileTap={{ scale: 0.95 }}
                >
                  Contact Us
                </motion.a>
              </div>
            </div>
          </motion.div>
        </motion.div>
      </div>
    </section>
  );
};

export default Faq;
